name: Build Library - Vendordep JSON

on:
  workflow_call:
    inputs:
      release-version:
        description: 'The version of the library to release.'
        default: '${{ github.ref_name }}'
        required: false
        type: string

      artifact-name:
        description: 'The name of the artifact to upload.'
        default: 'publish-outputs-json'
        required: false
        type: string

jobs:
  build-json:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build JSON with Gradle Wrapper
        run: ./gradlew vendordepJson
        env:
          releaseVersion: ${{ inputs.release-version }}

      - name: Upload Vendordep JSON
        uses: actions/upload-artifact@v4.3.1
        with:
          # Artifact name
          name: ${{ inputs.artifact-name }}
          # A file, directory or wildcard pattern that describes what to upload
          path: ./build/outputs/*.json
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
